config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :comments
  resources :albums
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  delete '/sessions/reset', to: 'sessions#reset_page_visits', as: 'page_reset'
  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_session'
  post '/sessions', to: 'sessions#create', as: 'sessions'
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :messages
    has_many :users, through: :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :message
    belongs_to :user


    validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :album
    has_many :comments



    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    has_many :comments
    has_many :albums, through: :messages


    validates :name, presence: true
    validates :username, presence: true
    validates :age, numericality: { greater_than_or_equal_to: 18 } #, message: 'You must be 18 Years or Older to Use Chatify' 
    
    #validates :album_id, uniqueness: {scope: user_id}
    #validates :password, presence: true



    has_secure_password
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

        def index
            @albums =  Album.all
            
            # hip_hop = albums.select {|album| album.genre == "Hip Hop"}
            # rock = albums.select {|album| album.genre == "Rock"}
            # randb = albums.select {|album| album.genre == "R&B"}
            # pop = albums.select {|album| album.genre == "Pop"}

            # @album_genres = [
            # {genre: "Hip Hop", albums: hip_hop}, 
            # {genre: "Rock", albums: rock}, 
            # {genre: "R&B", albums: randb},
            # {genre: "Pop", albums: pop}, 
            # ]


        end
    

        def show
            @album = Album.find(params[:id])
            @message = Message.new 
            @comment = Comment.new
           
        end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized?

    def find_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def authorized?
        redirect_to new_user_path unless find_current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new 
        @comment = Comment.new

        # @albums = Album.all
        # @users = User.all
    end
    
    def show
        #byebug
        @comment = Comment.find(params[:id])
        #@course = Course.find(params[:course_id])
        @album = Album.find(params[:id])
        

    end

    def create
        @current_user.comments << Comment.create(comment_params)
        @album = Message.find(params[:comment][:message_id]).album
        redirect_to album_path(@album)
    end

    

    private

    def comment_params
        params.require(:comment).permit(:message_id, :content)
    end
    
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

    def new 
        @forum = Forum.new

        @albums = Album.all
        @users = User.all
    end
    
    def show
        byebug
        @forum = Forum.find(params[:id])
        #@course = Course.find(params[:course_id])
        #@album = Album.find(params[:id])
        

    end

    def create
        @current_user.forums << Forum.create(forum_params)

        redirect_to user_path(@current_user)
    end

    

    private

    def forum_params
        params.require(:forum).permit(:user_id, :album_id)
    end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def index
        @user = User.find(session[:user_id])
        @messages = @user.messages
    end 

    # def new 
    #     @message = Message.new 
    #     # @user = User.find(session[:user_id])
    #     # @forums = @user.forums
    # end

    def create
        @user = User.find(session[:user_id])
        @message = Message.new(message_params)
        @message.user_id = @user.id
        #@message.forum_id = params[:forum_id] || @forum.id
     
        if @message.save 
            redirect_to album_path(@message.album)
        else 
            flash[:errors] = @message.errors.full_messages 
            redirect_to album_path(@message.album)
        end 
    end

    # def edit 
    #     @user = User.find(session[:user_id])
    #     @message  = @user.messages.find(params[:id])
    # end 


    # def update 
    #     @message  = message.find(params[:id])
    #     @message.update(message_params)

    #     if @message.save 
    #         redirect_to message_path(@message)
    #     else 
    #         flash[:errors] = @message.errors.full_messages 
    #         redirect_to edit_message_path
    #     end 
    # end 

    def destroy
        @message = Message.find(params[:id])
        @message.destroy
        
        redirect_to user_path(@current_user)
    end


    private 

    def message_params 
        params.require(:message).permit(:content, :album_id, :mood)
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authorized?, only: [:new, :create]
  
    def reset_page_visits
      cookies[:page_visits] = nil
      session.delete(:page_visits)
      
      redirect_back fallback_location: albums_path
    end 
    
    def logout 
      session.delete(:user_id)
      
      redirect_to new_user_path
    end 
  
    def new 
      render :new
    end 
  
    def create 
      
      user = User.find_by(username: params[:session][:username])
  
      if user && user.authenticate(params[:session][:password]) 
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        flash[:error] = "Password or Username incorrect"
        redirect_to new_session_path 
      end 
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized?, only: [:new, :create]

    def index
        @users =  User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end
    
    def edit
        @user = User.find(params[:id])
    end

    def update

        @user = User.find(params[:id])
 
         if @user.update(user_params)
             redirect_to user_path(@user)
 
         else  
             flash[:errors] = @user.errors.full_messages
             redirect_to edit_user_path(@user)
         end
     end
 
     def destroy
         @user = User.find(params[:id])
         @user.destroy
         redirect_to users_path
     end
     
    private

    def user_params
        params.require(:user).permit(:name, :age, :username, :password)

    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<%# @album_categories.each do |album| %>
<div class="parent">
<div class="div1">
 <h1 style="color: rgb(76, 161, 20);">Albums: <%# album[:category] %></h1>

<div class='index-container'>
    <% @albums.each do |album|%>

    <div class='index-title'>
        <a href="<%= album_path(album) %>">
         <img class="index-img" src="<%= album.img_url %>" alt="<%= album.title%>">
        </a>

    </div>
    <% end %>
</div>
</div>
</div>

app/views/albums/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

/*.parent {
display: grid;
grid-template-columns: repeat(6, 1fr);
grid-template-rows: repeat(6, 1fr);
grid-column-gap: 0px;
grid-row-gap: 0px;
}

.div1 { grid-area: 2 / 1 / 6 / 4; }
.div2 { grid-area: 2 / 4 / 5 / 7; }
.div3 { grid-area: 5 / 4 / 6 / 7; }*/

.parent {
display: grid;
grid-template-columns: repeat(2, 1fr);
grid-template-rows: repeat(3, 1fr);
grid-column-gap: 0px;
grid-row-gap: 0px;
}

.div1 { grid-area: 1 / 1 / 4 / 2; }
.div2 { grid-area: 1 / 2 / 4 / 3; }
.div3 { grid-area: 3 / 2 / 4 / 3; }

.center {
  margin: auto;
  width: 60%;
  border: 0;
  padding: 10px;
  text-align: center;

}


h2 {
  text-align: left;
  white-space: wrap;
  margin: 0;
  padding: 0;
  letter-spacing: 0px;
  
}

h3 {
  text-align: right;
  white-space: wrap;
  margin: 1;
  padding: 1;
 
}

img {
  display: block;
  margin-left: auto;
  margin-right: auto;
}

#overflowTest {
  background: 0;
  color: white;
  padding: 10px;
  width: 80%;
  height: 300px;
  overflow: auto;
  border: 0px ;
}

a:link {
  text-decoration: none;
  color: #646464;
}
a:visited {
  color: #646464;
}




</style>
</head>
<body>


<div class="parent">
<div class="div1" > 

<div class="center">

<br>

<img src="<%= @album.img_url %>" alt="<%= @album.title %>"  style="width:100%; height: 100% "><br>
  <h1  class="title1"><%= @album.artist %></h1>
  <h1 class="title1" style="color: #4CAF50;"><%= @album.title %></h1>
<p class="title1">Genre: <%= @album.genre %></p>
<p class="title1">Release Year: <%= @album.release_year %></p>


</div>
</div>
<br>

<div class="div2" id="overflowTest"> 
<%#If it's broke this is where you did it a;lskdjf;alskdjfl;akjdsf;lajsdlkfjadls;kjfal;sdjfl;asdkjfl;jksdl;fjkalsd;kjfa;sdljfa;lsdkjf;lajksdf;lasdjfalsd;jkfl;ajdsfja;ldsjf;aldsfj%>
<div class="whatsapp-background">

<% @album.messages.each do |message| %>
  <h2><a><p style="color: grey;"><%= link_to message.user.username , user_path(message.user) %>:</p></a></h2>
  <h2 class="<%= message.mood %>" style="font-size: 12px; font-weight: normal;"> <%= message.content %></h2>
    <h2><% message.comments.each do |comment| %></h2>
      <h3 style="font-size: 12px; color: grey;"><p><%= link_to comment.user.username, user_path(comment.user) %></p></h3>
    <p><h3 style="background-color: grey; border-radius: 12px; padding: 10px ; width: 98%; margin: 3; font-size: 12px; font-weight: normal;"> <%= comment.content %></p></h3>
    <% end %>

    <div class='form-container'>
      <% if flash[:error] %>
        <p><%= flash[:error] %></p>
      <% end %>
      <h3><%= form_for @comment do |f| %></h3>
        <h3><% f.hidden_field :content %></h3>
        <h3><%= f.text_field :content %></h3>

       <h3> <%= f.hidden_field :message_id, value: message.id %></h3>
      
        <h3><%= f.submit "Comment", :class => 'submit2' %></h3>
    
      <% end %>
    </div>
<% end %>
<%#And this is his friend laksdjfaa;lskdjf;alskdjfl;akjdsf;lajsdlkfjadls;kjfal;sdjfl;asdkjfl;jksdl;fjkalsd;kjfa;sdljfa;lsdk %>
</div>


</div>
<div class="div3" >
 <div >
<h2 style="color: #646464">Join the Conversation Here:</h2>

 <p><%= form_for @message do |f| %></p>

    <%= f.label :mood %>
    <%= f.select :mood, [['positive'],['mixed'],['negative']] %>
    
    <% f.label :content %>
<%= f.text_field :content, :class => 'form'  %>
    
   <p> <%= f.hidden_field :album_id, value: @album.id %></p>
   
   <p> <%= f.submit "Submit Message", :class => 'submit' %></p>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
       <h3> <p><%= error %></p>
      <% end %>
    <% end %>
  
<% end %>
</div>
</div>
</div>
</div>




</body>
</html>

app/views/forums/show.html.erb
<img src="<%= @forum.album.img_url %>" alt="<%= @forum.album.title %>">
<h1><%= @forum.album.title %></h1>
<p><%= @forum.album.genre %></p>




    <% @forum.messages.each do |message| %>
        <%= message.comment %>
        <br>
    <% end %>


<%= link_to 'Add a Comment', new_message_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

     <style>
  

  </style>
  </head>
 

  <body>
    <div class="sidenav">
    <nav>
        <ul>
          

          

          <% if @current_user %>
           <li class="nav-tabs-right"><%= link_to "All Albums", albums_path %></li>
            <li class="nav-tabs-right"><%= link_to "Profile Page", user_path(@current_user) %></li>
            <li class="nav-tabs-right"><%= link_to "Logout", logout_path, method: :delete %></li>

          <% else %>
            <li class="nav-tabs-right"><%= link_to "Sign Up", new_user_path %></li>
            <li class="nav-tabs-right"><%= link_to "Login", new_session_path %></li>
          <% end %>

        </ul>

      </nav>
      </div>
      <div class="main">
    <%= yield %>
    </div>

              



    <div class="parentlogo">
      <div class="divlogo"> 



</div>
</div>

          <img class="logo-pic" style="box-shadow: 0px 0px 0px 0px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Chatify1.png/240px-Chatify1.png" alt="Chatify Logo">
          <img class="logo-pic-text" style="box-shadow: 0px 0px 0px 0px" src="https://upload.wikimedia.org/wikipedia/commons/8/8f/ChatifyName.png" alt="Chatify Logo Text">
  </body>
  <footer class="footerlogo">

  </footer>
  
</html>

app/views/messages/edit.html.erb
<h1> Edit Your Message Here</h1>

<%= form_for @message do |f| %>

    <%= f.label :mood %>
    <%= f.select :mood, [['Happy'],['Sad'],['Angry']] %>
    <br>
    <%= f.label :comment %>
    <%= f.text_field :comment %>
    <br>
    <%= f.label :forum_id  %>
    <%= f.text_field :forum_id %>
    <%# f.radio_button :forum_id, 'Marvin Gaye' %>
   
    <%= f.submit "Submit Message" %>
  
<% end %>

app/views/messages/index.html.erb
<div class='index-container'>
<% .each do |album|%>

<div class='index-title'>
<a href="<%= album_path(album) %>">
<img class="index-img" src="<%= album.img_url %>" alt="<%= album.title%>">
</a>

</div>
<% end %>
</div>

app/views/messages/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>

<%= form_for @message do |f| %>

    <%= f.label :mood %>
    <%= f.select :mood, [['Happy'],['Sad'],['Angry']] %>
    <br>
    <%= f.label :comment %>
    <%= f.text_field :comment %>
    <br>
    <%= f.submit "Submit Message" %>
  
<% end %>

app/views/users/edit.html.erb
<div class="parent1">
<div class="div11">




<div class='edit-user'>
    <h1 style="color: #4CAF50;">Edit Your Chatify Account</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p style="color: rgb(194, 70, 62);"><%= error %></p>
    <% end %>
    <% end %>

    <%= form_for @user do |f| %>
        <div class='sessions-input'>
           <p> <%= f.label :name %></p>
            <%= f.text_field :name %>
        </div>

        <div class='sessions-input'>
           <p> <%= f.label :age %></p>
           <%= f.number_field :age %>
        </div>

        <div class='sessions-input'>
            <p><%= f.label :username %></p>
          <%= f.text_field :username %> 
        </div>

        <div class='sessions-input'>
           <p> <%= f.label :password %></p>
           <p> <%= f.text_field :password %></p>
        </div>

        <%= f.submit "Update Profile", class: 'profile-btn' %>
    <% end %>

</div>

<%= button_to 'Delete Account', user_path(@user), method: :delete, class: 'profile-btn' %><br>

</div>
</div>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

</style>
</head>
<body>
<div class="parent1">
<div class="div11">


<div class='sessions-container'>
    <h1 style="color: #4CAF50;">Sign Up for your Chatify Account</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p style=" color: rgb(194, 70, 62);"><%= error %></p>
     <% end %>
    <% end %>

    <%= form_for @user do |f| %>
        <div class='sessions-input'>
           <p> <%= f.label :name %></p>
            <%= f.text_field :name %>
        </div>

        <div class='sessions-input'>
            <p><%= f.label :age %></p>
            <%= f.number_field :age %>
        </div>

        <div class='sessions-input'>
            <p><%= f.label :username %></p>
            <%= f.text_field :username %>
        </div>

        <div class='sessions-input'>
            <p><%= f.label :password %></p>
            <p><%= f.password_field :password %></p>
        </div>

        <%= f.submit "Create Account", :class => 'submit3' %>
    <% end %>

    <div class="div21">


    </div>

    </div>
</div>

</div>
</div>

</body>
</html>

app/views/users/show.html.erb
<div>
    <% if @user != @current_user %>
        <h2>Profile for: <%= @user.username %></h2>

        <div class="forums-list">
                    <h3>Albums Reviewed by: <%= @user.username %></h3>
                    <div class="index-container">
                        <% @user.albums.uniq.each do |album| %>
                            <div class="show-tile">
                                <a href="<%= album_path(album) %>">
                                    <img class="index-img" src="<%= album.img_url %>" alt="<%= album.title %>">
                                </a>
                            </div>
                        <% end %>
                    </div>
                </div>
    <% else %>
       


            <div class="profile-info">
                <% if flash[:error] %>
                <p><%= flash[:error] %></p>
                <% end %>


                <h1 style="color: #4CAF50;">Welcome <%= @user.name %></h1>
                <h2>Username: <%= @user.username %></h2>
                <%= button_to 'Edit Profile', edit_user_path, method: :get, class: "profile-btn" %>
                
            </div>
            <% if @user.albums.count != 0 %>
                <div class="forums-list">
                    <h3>Albums You've Reviewed:</h3>
                    <div class="index-container1">
                        <% @user.albums.uniq.each do |album| %>
                            <div class="show-tile">
                                <a href="<%= album_path(album) %>">
                                    <img class="index-img" src="<%= album.img_url %>" alt="<%= album.title %>">
                                </a>
                            </div>
                        <% end %>
                    </div>
                </div>
            <% else %>
                <h3> You Haven't Reviewed Any Albums Yet!</h3>
                <h3 style="color: #4CAF50;"> Click <%= link_to 'HERE', albums_path %> to Write Your First Review!</h3>
            <% end %>


    <% end %>
</div>